spring.application.name=eduplus

spring.datasource.url=jdbc:h2:file:./data/eduplusdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# Deixe true para a equipe ver no console os SELECTs repetidos (o N+1)
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8083
